import type { Config } from 'drizzle-kit';

import { ormConfig } from '@/configs';

export default {
	schema: './src/migrations/schemas/schema.ts',
	out: './src/migrations/schemas',
	driver: 'mysql2',
	dbCredentials: {
		database: ormConfig.database,
		host: ormConfig.host,
		user: ormConfig.user,
		password: ormConfig.password,
		port: ormConfig.port,
	},
	schemaFilter: ['internals'],
	tablesFilter: [
		// 'api_containers',
		// 'answers',
		'bots',
		'bots_interaction_history',
		'bots_whatsapps',
		// 'contacts',
		// 'contact_tags',
		// 'companies',
		// 'company_subscription',
		// 'greetings_message',
		// 'goodbye_message',
		// 'historic_tickets',
		// 'plans',
		'profiles',
		'questions',
		// 'schedule_messages',
		// 'schedule_message_cadence',
		// 'schedulemessages_contacts',
		// 'schedule_message_csv',
		// 'schedulemessages_sendMessages',
		// 'schedulemessages_whatsapp',
		// 'researchs',
		// 'researchs_historic',
		// 'statuses',
		// 'tags',
		// 'tickets',
		// 'templates',
		'users',
		// 'whatsapps',
		// 'sms_credit',
		// 'email_credit',
		// 'email_company',
	],
} satisfies Config;
